---
title: "Mcap_parents Data Analysis"
author: "Shayle Matsuda"
date: "1/17/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Script analyzing ITS2 for Mcap parents in Kaneohe Bay
Data processed in Symportal

```{r}
#library
library(janitor)
library(phyloseq)  # source('http://bioconductor.org/biocLite.R'); biocLite('phyloseq')
library(zoo)
library(stringr)
library(vegan)
library(multcompView)
library("ggpubr")
library(readxl)
library("writexl")
library(tidyverse)

#load in data:
load("data/coral_phyloseq.RData")
```
Subset by colony DIV, data setup
```{r} 
sample_variables(coralDIV2.prune) #what are the variables

Mcap_10 <- subset_samples(coralDIV2.prune, Colony =="10") #Subset by colony  
Mcap_120 <- subset_samples(coralDIV2.prune, Colony =="120") #Subset by colony  
Mcap_1212 <- subset_samples(coralDIV2.prune, Colony =="1212") #Subset by colony  
Mcap_1213 <- subset_samples(coralDIV2.prune, Colony =="1213") #Subset by colony  
Mcap_1221 <- subset_samples(coralDIV2.prune, Colony =="1221") #Subset by colony 
Mcap_1222 <- subset_samples(coralDIV2.prune, Colony =="1222") #Subset by colony 
Mcap_1226<- subset_samples(coralDIV2.prune, Colony =="1226") #Subset by colony 
Mcap_1255 <- subset_samples(coralDIV2.prune, Colony =="1255") #Subset by colony 
Mcap_1261 <- subset_samples(coralDIV2.prune, Colony =="1261") #Subset by colony 
Mcap_1263 <- subset_samples(coralDIV2.prune, Colony =="1263") #Subset by colony 
Mcap_1264 <- subset_samples(coralDIV2.prune, Colony =="1264") #Subset by colony 
Mcap_127 <- subset_samples(coralDIV2.prune, Colony =="127") #Subset by colony 
Mcap_1292 <- subset_samples(coralDIV2.prune, Colony =="1292") #Subset by colony 
Mcap_141 <- subset_samples(coralDIV2.prune, Colony =="141") #Subset by colony 
Mcap_146 <- subset_samples(coralDIV2.prune, Colony =="146") #Subset by colony 
Mcap_151 <- subset_samples(coralDIV2.prune, Colony =="151") #Subset by colony 
Mcap_160 <- subset_samples(coralDIV2.prune, Colony =="160") #Subset by colony 
Mcap_211 <- subset_samples(coralDIV2.prune, Colony =="211") #Subset by colony 
Mcap_258 <- subset_samples(coralDIV2.prune, Colony =="258") #Subset by colony 
Mcap_277 <- subset_samples(coralDIV2.prune, Colony =="277") #Subset by colony 
Mcap_306 <- subset_samples(coralDIV2.prune, Colony =="306") #Subset by colony 
Mcap_315 <- subset_samples(coralDIV2.prune, Colony =="315") #Subset by colony 
Mcap_322 <- subset_samples(coralDIV2.prune, Colony =="322") #Subset by colony 
Mcap_32 <- subset_samples(coralDIV2.prune, Colony =="32") #Subset by colony 
Mcap_333 <- subset_samples(coralDIV2.prune, Colony =="333") #Subset by colony 
Mcap_353 <- subset_samples(coralDIV2.prune, Colony =="353") #Subset by colony 
Mcap_386 <- subset_samples(coralDIV2.prune, Colony =="386") #Subset by colony 
Mcap_479 <- subset_samples(coralDIV2.prune, Colony =="479") #Subset by colony 
Mcap_485 <- subset_samples(coralDIV2.prune, Colony =="485") #Subset by colony 
Mcap_497 <- subset_samples(coralDIV2.prune, Colony =="497") #Subset by colony 
Mcap_556 <- subset_samples(coralDIV2.prune, Colony =="556") #Subset by colony 
Mcap_565 <- subset_samples(coralDIV2.prune, Colony =="565") #Subset by colony 
Mcap_576 <- subset_samples(coralDIV2.prune, Colony =="576") #Subset by colony 
Mcap_586 <- subset_samples(coralDIV2.prune, Colony =="586") #Subset by colony 
Mcap_609 <- subset_samples(coralDIV2.prune, Colony =="609") #Subset by colony 
Mcap_612 <- subset_samples(coralDIV2.prune, Colony =="612") #Subset by colony 
Mcap_620 <- subset_samples(coralDIV2.prune, Colony =="620") #Subset by colony 
Mcap_632 <- subset_samples(coralDIV2.prune, Colony =="632") #Subset by colony 
Mcap_649 <- subset_samples(coralDIV2.prune, Colony =="649") #Subset by colony 
Mcap_670 <- subset_samples(coralDIV2.prune, Colony =="670") #Subset by colony 
Mcap_677 <- subset_samples(coralDIV2.prune, Colony =="677") #Subset by colony 
Mcap_684 <- subset_samples(coralDIV2.prune, Colony =="684") #Subset by colony 
Mcap_70 <- subset_samples(coralDIV2.prune, Colony =="70") #Subset by colony   
Mcap_742 <- subset_samples(coralDIV2.prune, Colony =="742") #Subset by colony 
Mcap_745 <- subset_samples(coralDIV2.prune, Colony =="745") #Subset by colony 
Mcap_748 <- subset_samples(coralDIV2.prune, Colony =="748") #Subset by colony 
Mcap_78 <- subset_samples(coralDIV2.prune, Colony =="78") #Subset by colony 
Mcap_823 <- subset_samples(coralDIV2.prune, Colony =="823") #Subset by colony 
Mcap_83 <- subset_samples(coralDIV2.prune, Colony =="83") #Subset by colony 
Mcap_95 <- subset_samples(coralDIV2.prune, Colony =="95") #Subset by colony 
```
PROFILES
Subset by colony PROFILE, data setup
```{r}  

library("RColorBrewer")
getPalette = colorRampPalette(brewer.pal(8, "Dark2"))

speciesList = unique(tax_table(coral2.prune)[,"its2_type_profile"])
speciesPalette = getPalette(length(speciesList))
names(speciesPalette) = speciesList

#scale_color_manual(values=speciesPalette)
#scale_fill_manual(values= speciesPalette)

#this works but you need better pallet color = grDevices::colors()[grep('gr(a|e)y', grDevices::colors(), invert = T)]

sample_variables(coral2.prune) #what are the variables
#sample_variables(coral2) # use to check low samps for geno with only 1

Pro_Mcap_A <- subset_samples(coral2.prune, Replicate =="A") #Subset by colony  
#Pro_Mcap_A <- subset_samples(coral2, Replicate =="A") #check low samp

#something in sd is off so blank spaces inserted into colony name
Pro_Mcap_10 <- subset_samples(coral2.prune, Colony=="  10") #Subset by colony  
Pro_Mcap_120 <- subset_samples(coral2.prune, Colony ==" 120") #Subset by colony  
Pro_Mcap_1212 <- subset_samples(coral2.prune, Colony =="1212") #Subset by colony  
Pro_Mcap_1213 <- subset_samples(coral2.prune, Colony =="1213") #Subset by colony  
Pro_Mcap_1221 <- subset_samples(coral2.prune, Colony =="1221") #Subset by colony 
Pro_Mcap_1222 <- subset_samples(coral2.prune, Colony =="1222") #Subset by colony 
Pro_Mcap_1226<- subset_samples(coral2.prune, Colony =="1226") #Subset by colony 
Pro_Mcap_1255 <- subset_samples(coral2.prune, Colony =="1255") #Subset by colony 
Pro_Mcap_1261 <- subset_samples(coral2.prune, Colony =="1261") #Subset by colony o
Pro_Mcap_1263 <- subset_samples(coral2.prune, Colony =="1263") #Subset by colony 
Pro_Mcap_1264 <- subset_samples(coral2.prune, Colony =="1264") #Subset by colony 
Pro_Mcap_127 <- subset_samples(coral2.prune, Colony ==" 127") #Subset by colony 
Pro_Mcap_1292 <- subset_samples(coral2.prune, Colony =="1292") #Subset by colony 
Pro_Mcap_141 <- subset_samples(coral2.prune, Colony ==" 141") #Subset by colony 
Pro_Mcap_146 <- subset_samples(coral2.prune, Colony ==" 146") #Subset by colony 
Pro_Mcap_151 <- subset_samples(coral2.prune, Colony ==" 151") #Subset by colony 
Pro_Mcap_160 <- subset_samples(coral2.prune, Colony ==" 160") #Subset by colony 
Pro_Mcap_211 <- subset_samples(coral2.prune, Colony ==" 211") #Subset by colony 
Pro_Mcap_258 <- subset_samples(coral2.prune, Colony ==" 258") #Subset by colony 
Pro_Mcap_277 <- subset_samples(coral2.prune, Colony ==" 277") #Subset by colony 
Pro_Mcap_306 <- subset_samples(coral2.prune, Colony ==" 306") #Subset by colony 
Pro_Mcap_315 <- subset_samples(coral2.prune, Colony ==" 315") #Subset by colony 
Pro_Mcap_322 <- subset_samples(coral2.prune, Colony ==" 322") #Subset by colony 
Pro_Mcap_32 <- subset_samples(coral2.prune, Colony =="  32") #Subset by colony 
Pro_Mcap_333 <- subset_samples(coral2.prune, Colony ==" 333") #Subset by colony 
Pro_Mcap_353 <- subset_samples(coral2.prune, Colony ==" 353") #Subset by colony 
Pro_Mcap_386 <- subset_samples(coral2.prune, Colony ==" 386") #Subset by colony 
Pro_Mcap_479 <- subset_samples(coral2.prune, Colony ==" 479") #Subset by colony 
Pro_Mcap_485 <- subset_samples(coral2.prune, Colony ==" 485") #Subset by colony 
Pro_Mcap_497 <- subset_samples(coral2.prune, Colony ==" 497") #Subset by colony 
Pro_Mcap_556 <- subset_samples(coral2.prune, Colony ==" 556") #Subset by colony 
Pro_Mcap_565 <- subset_samples(coral2.prune, Colony ==" 565") #Subset by colony 
Pro_Mcap_576 <- subset_samples(coral2.prune, Colony ==" 576") #Subset by colony 
Pro_Mcap_586 <- subset_samples(coral2.prune, Colony ==" 586") #Subset by colony 
Pro_Mcap_609 <- subset_samples(coral2.prune, Colony ==" 609") #Subset by colony 
Pro_Mcap_612 <- subset_samples(coral2.prune, Colony ==" 612") #Subset by colony 
Pro_Mcap_620 <- subset_samples(coral2.prune, Colony ==" 620") #Subset by colony 
Pro_Mcap_632 <- subset_samples(coral2.prune, Colony ==" 632") #Subset by colony 
Pro_Mcap_649 <- subset_samples(coral2.prune, Colony ==" 649") #Subset by colony 
Pro_Mcap_670 <- subset_samples(coral2.prune, Colony ==" 670") #Subset by colony 
Pro_Mcap_677 <- subset_samples(coral2.prune, Colony ==" 677") #Subset by colony 
Pro_Mcap_684 <- subset_samples(coral2.prune, Colony ==" 684") #Subset by colony 
Pro_Mcap_70 <- subset_samples(coral2.prune, Colony =="  70") #Subset by colony     
Pro_Mcap_742 <- subset_samples(coral2.prune, Colony ==" 742") #Subset by colony 
Pro_Mcap_745 <- subset_samples(coral2.prune, Colony ==" 745") #Subset by colony 
Pro_Mcap_748 <- subset_samples(coral2.prune, Colony ==" 748") #Subset by colony 
Pro_Mcap_78 <- subset_samples(coral2.prune, Colony =="  78") #Subset by colony 
Pro_Mcap_823 <- subset_samples(coral2.prune, Colony ==" 823") #Subset by colony 
Pro_Mcap_83 <- subset_samples(coral2.prune, Colony =="  83") #Subset by colony 
Pro_Mcap_95 <- subset_samples(coral2.prune, Colony =="  95") #Subset by colony 

#check low samples that were culled for samples with only n=1
#Pro_Mcap_1263 <- subset_samples(coral2, Colony =="1263") #Subset by colony 
#Pro_Mcap_146 <- subset_samples(coral2, Colony ==" 146") #Subset by colony 
#Pro_Mcap_70 <- subset_samples(coral2, Colony =="  70") #Subset by colony     
```

Plots  by CLADE
```{r}   
#scale_color_manual(values=speciesPalette)
#scale_fill_manual(values= speciesPalette)
#for the legend
 plot_bar(Pro_Mcap_10,fill = "clade")+
      geom_bar(aes(color=clade, fill=clade), stat="identity", position="stack")

Pro_Mcap_10_plot<-plot_bar(Pro_Mcap_10, "Replicate", fill="clade", title="10")+
   theme(legend.position="none");Pro_Mcap_10_plot
Pro_Mcap_120_plot<-plot_bar(Pro_Mcap_120, "Replicate", fill="clade", title="120")+
   theme(legend.position="none");Pro_Mcap_120_plot
Pro_Mcap_1212_plot<-plot_bar(Pro_Mcap_1212, "Replicate", fill="clade", title="1212")+
   theme(legend.position="none");Pro_Mcap_1212_plot
Pro_Mcap_1213_plot<-plot_bar(Pro_Mcap_1213, "Replicate", fill="clade", title="1213")+
   theme(legend.position="none");Pro_Mcap_1213_plot

Pro_Mcap_1221_plot<-plot_bar(Pro_Mcap_1221, "Replicate", fill="clade", title="1221")+
   theme(legend.position="none");Pro_Mcap_1221_plot
Pro_Mcap_1222_plot<-plot_bar(Pro_Mcap_1222, "Replicate", fill="clade", title="1222")+
   theme(legend.position="none");Pro_Mcap_1222_plot
Pro_Mcap_1226_plot<-plot_bar(Pro_Mcap_1226, "Replicate", fill="clade", title="1226")+
   theme(legend.position="none");Pro_Mcap_1226_plot
Pro_Mcap_1255_plot<-plot_bar(Pro_Mcap_1255, "Replicate", fill="clade", title="1255")+
   theme(legend.position="none");Pro_Mcap_1255_plot
Pro_Mcap_1261_plot<-plot_bar(Pro_Mcap_1261, "Replicate", fill="clade", title="1261")+
   theme(legend.position="none");Pro_Mcap_1261_plot
Pro_Mcap_1263_plot<-plot_bar(Pro_Mcap_1263, "Replicate", fill="clade", title="1263")+
   theme(legend.position="none");Pro_Mcap_1263_plot
Pro_Mcap_1264_plot<-plot_bar(Pro_Mcap_1264, "Replicate", fill="clade", title="1264")+
   theme(legend.position="none");Pro_Mcap_1264_plot
Pro_Mcap_127_plot<-plot_bar(Pro_Mcap_127, "Replicate", fill="clade", title="127")+
   theme(legend.position="none");Pro_Mcap_127_plot
Pro_Mcap_1292_plot<-plot_bar(Pro_Mcap_1292, "Replicate", fill="clade", title="1292")+
   theme(legend.position="none");Pro_Mcap_1292_plot
Pro_Mcap_141_plot<-plot_bar(Pro_Mcap_141, "Replicate", fill="clade", title="141")+
   theme(legend.position="none");Pro_Mcap_141_plot
Pro_Mcap_146_plot<-plot_bar(Pro_Mcap_146, "Replicate", fill="clade", title="146")+
   theme(legend.position="none");Pro_Mcap_146_plot
Pro_Mcap_151_plot<-plot_bar(Pro_Mcap_151, "Replicate", fill="clade", title="151")+
   theme(legend.position="none");Pro_Mcap_151_plot
Pro_Mcap_160_plot<-plot_bar(Pro_Mcap_160, "Replicate", fill="clade", title="160")+
   theme(legend.position="none");Pro_Mcap_160_plot
Pro_Mcap_211_plot<-plot_bar(Pro_Mcap_211, "Replicate", fill="clade", title="211")+
   theme(legend.position="none");Pro_Mcap_211_plot
Pro_Mcap_258_plot<-plot_bar(Pro_Mcap_258, "Replicate", fill="clade", title="258")+
   theme(legend.position="none");Pro_Mcap_258_plot
Pro_Mcap_277_plot<-plot_bar(Pro_Mcap_277, "Replicate", fill="clade", title="277")+
   theme(legend.position="none");Pro_Mcap_277_plot
Pro_Mcap_306_plot<-plot_bar(Pro_Mcap_306, "Replicate", fill="clade", title="306")+
   theme(legend.position="none");Pro_Mcap_306_plot
Pro_Mcap_315_plot<-plot_bar(Pro_Mcap_315, "Replicate", fill="clade", title="315")+
   theme(legend.position="none");Pro_Mcap_315_plot
Pro_Mcap_322_plot<-plot_bar(Pro_Mcap_322, "Replicate", fill="clade", title="22")+
   theme(legend.position="none");Pro_Mcap_322_plot
Pro_Mcap_32_plot<-plot_bar(Pro_Mcap_32, "Replicate", fill="clade", title="32")+
   theme(legend.position="none");Pro_Mcap_32_plot
Pro_Mcap_333_plot<-plot_bar(Pro_Mcap_333, "Replicate", fill="clade", title="333")+
   theme(legend.position="none");Pro_Mcap_333_plot
Pro_Mcap_353_plot<-plot_bar(Pro_Mcap_353, "Replicate", fill="clade", title="353")+
   theme(legend.position="none");Pro_Mcap_353_plot
Pro_Mcap_386_plot<-plot_bar(Pro_Mcap_386, "Replicate", fill="clade", title="386")+
   theme(legend.position="none");Pro_Mcap_386_plot
Pro_Mcap_479_plot<-plot_bar(Pro_Mcap_479, "Replicate", fill="clade", title="479")+
   theme(legend.position="none");Pro_Mcap_479_plot
Pro_Mcap_485_plot<-plot_bar(Pro_Mcap_485, "Replicate", fill="clade", title="485")+
   theme(legend.position="none");Pro_Mcap_485_plot
Pro_Mcap_497_plot<-plot_bar(Pro_Mcap_497, "Replicate", fill="clade", title="497")+
   theme(legend.position="none");Pro_Mcap_497_plot

Pro_Mcap_556_plot<-plot_bar(Pro_Mcap_556, "Replicate", fill="clade", title="556")+
   theme(legend.position="none");Pro_Mcap_556_plot
Pro_Mcap_565_plot<-plot_bar(Pro_Mcap_565, "Replicate", fill="clade", title="565")+
   theme(legend.position="none");Pro_Mcap_565_plot
Pro_Mcap_576_plot<-plot_bar(Pro_Mcap_576, "Replicate", fill="clade", title="576")+
   theme(legend.position="none");Pro_Mcap_576_plot
Pro_Mcap_586_plot<-plot_bar(Pro_Mcap_586, "Replicate", fill="clade", title="586")+
   theme(legend.position="none");Pro_Mcap_586_plot

Pro_Mcap_609_plot<-plot_bar(Pro_Mcap_609, "Replicate", fill="clade", title="609")+
   theme(legend.position="none");Pro_Mcap_609_plot
Pro_Mcap_612_plot<-plot_bar(Pro_Mcap_612, "Replicate", fill="clade", title="612")+
   theme(legend.position="none");Pro_Mcap_612_plot
Pro_Mcap_620_plot<-plot_bar(Pro_Mcap_620, "Replicate", fill="clade", title="620")+
   theme(legend.position="none");Pro_Mcap_620_plot
Pro_Mcap_632_plot<-plot_bar(Pro_Mcap_632, "Replicate", fill="clade", title="632")+
   theme(legend.position="none");Pro_Mcap_632_plot
Pro_Mcap_649_plot<-plot_bar(Pro_Mcap_649, "Replicate", fill="clade", title="649")+
   theme(legend.position="none");Pro_Mcap_649_plot
Pro_Mcap_670_plot<-plot_bar(Pro_Mcap_670, "Replicate", fill="clade", title="670")+
   theme(legend.position="none");Pro_Mcap_670_plot
Pro_Mcap_677_plot<-plot_bar(Pro_Mcap_677, "Replicate", fill="clade", title="677")+
   theme(legend.position="none");Pro_Mcap_677_plot
Pro_Mcap_684_plot<-plot_bar(Pro_Mcap_684, "Replicate", fill="clade", title="684")+
   theme(legend.position="none");Pro_Mcap_684_plot
Pro_Mcap_70_plot<-plot_bar(Pro_Mcap_70, "Replicate", fill="clade", title="70")+
   theme(legend.position="none");Pro_Mcap_70_plot
Pro_Mcap_742_plot<-plot_bar(Pro_Mcap_742, "Replicate", fill="clade", title="742")+
   theme(legend.position="none");Pro_Mcap_742_plot
Pro_Mcap_748_plot<-plot_bar(Pro_Mcap_748, "Replicate", fill="clade", title="748")+
   theme(legend.position="none");Pro_Mcap_748_plot
Pro_Mcap_78_plot<-plot_bar(Pro_Mcap_78, "Replicate", fill="clade", title="78")+
   theme(legend.position="none");Pro_Mcap_78_plot
Pro_Mcap_823_plot<-plot_bar(Pro_Mcap_823, "Replicate", fill="clade", title="823")+
   theme(legend.position="none");Pro_Mcap_823_plot
Pro_Mcap_83_plot<-plot_bar(Pro_Mcap_83, "Replicate", fill="clade", title="83")+
   theme(legend.position="none");Pro_Mcap_83_plot
Pro_Mcap_95_plot<-plot_bar(Pro_Mcap_95, "Replicate", fill="clade", title="95")+
   theme(legend.position="none");Pro_Mcap_95_plot

Mcap_DIV_PRO_plot1 <- ggarrange(Pro_Mcap_10_plot,Pro_Mcap_120_plot,Pro_Mcap_1212_plot,Pro_Mcap_1213_plot,Pro_Mcap_1221_plot,Pro_Mcap_1222_plot,Pro_Mcap_1226_plot,Pro_Mcap_1255_plot,
                    #labels = c("A", "B", "C","D","E","F","G","H"),
                    ncol = 4, nrow = 3);Mcap_DIV_PRO_plot1

Mcap_DIV_PRO_plot2 <- ggarrange(Pro_Mcap_1261_plot,Pro_Mcap_1263_plot,Pro_Mcap_1264_plot,Pro_Mcap_127_plot,Pro_Mcap_1292_plot,Pro_Mcap_141_plot,Pro_Mcap_146_plot,Pro_Mcap_151_plot,
                    #labels = c("A", "B", "C","D","E","F","G","H"),
                    ncol = 4, nrow = 3);Mcap_DIV_PRO_plot2

Mcap_DIV_PRO_plot3 <- ggarrange(Pro_Mcap_160_plot,Pro_Mcap_211_plot,Pro_Mcap_258_plot,Pro_Mcap_277_plot,Pro_Mcap_306_plot,Pro_Mcap_315_plot,Pro_Mcap_322_plot,Pro_Mcap_32_plot,
                    #labels = c("A", "B", "C","D","E","F","G","H"),
                    ncol = 4, nrow = 3);Mcap_DIV_PRO_plot3

Mcap_DIV_PRO_plot4 <- ggarrange(Pro_Mcap_333_plot,Pro_Mcap_353_plot,Pro_Mcap_386_plot,Pro_Mcap_479_plot,Pro_Mcap_485_plot,Pro_Mcap_497_plot,Pro_Mcap_556_plot,Pro_Mcap_565_plot,
                    #labels = c("A", "B", "C","D","E","F","G","H"),
                    ncol = 4, nrow = 3);Mcap_DIV_PRO_plot4

Mcap_DIV_PRO_plot5 <- ggarrange(Pro_Mcap_576_plot,Pro_Mcap_586_plot,Pro_Mcap_609_plot,Pro_Mcap_612_plot,Pro_Mcap_620_plot,Pro_Mcap_632_plot,Pro_Mcap_649_plot,Pro_Mcap_670_plot,
                    #labels = c("A", "B", "C","D","E","F","G","H"),
                    ncol = 4, nrow = 3);Mcap_DIV_PRO_plot5

Mcap_DIV_PRO_plot6 <- ggarrange(Pro_Mcap_677_plot,Pro_Mcap_684_plot,Pro_Mcap_70_plot,Pro_Mcap_742_plot,Pro_Mcap_748_plot,Pro_Mcap_78_plot,Pro_Mcap_823_plot,Pro_Mcap_83_plot,
                    #labels = c("A", "B", "C","D","E","F","G","H"),
                    ncol = 4, nrow = 3);Mcap_DIV_PRO_plot6

Mcap_DIV_PRO_plot7 <- ggarrange(Pro_Mcap_95_plot,
                    #labels = c("A", "B", "C","D","E","F","G","H"),
                    ncol = 4, nrow = 3);Mcap_DIV_PRO_plot7

```

Identify relative abundance of C:D for each genotype
```{r}
#do tax glom in the data to group C and D 
data.clade<- tax_glom(coral2.prune, taxrank="clade") 

## calcualte average percent C and D per genotype
#read in by clade %
 clade.percent<-read.csv("data/ford mcap clades 1299cutoff.csv")
 cp<-clade.percent
 cp<-tibble(cp)
 
 cp<-cp%>%
  group_by(genotype) %>%
   summarise(n=n(),meanC=mean(C), meanD=mean(D))
  
 cp<-cp%>% 
   arrange(meanC)
  
cp2 <- cp %>%
  pivot_longer(cols = 3:4, names_to = "clade", values_to = "percent")
#write.csv(cp,"geno.clades.csv")  
   
#plots
 p<-ggplot(data=cp2,aes(x=reorder(genotype,-percent), y=percent, fill=clade))
   p + geom_bar(position = "fill", stat="identity")
```
 
Other data vis:
Plots PRO
```{r} 
#for the legend
Pro_Mcap_10_plot<-plot_bar(Pro_Mcap_10, "Replicate", fill="its2_type_profile", title="10")+
   theme(legend.position="none");Pro_Mcap_10_plot
Pro_Mcap_120_plot<-plot_bar(Pro_Mcap_120, "Replicate", fill="its2_type_profile", title="120")+
   theme(legend.position="none");Pro_Mcap_120_plot
Pro_Mcap_1212_plot<-plot_bar(Pro_Mcap_1212, "Replicate", fill="its2_type_profile", title="1212")+
   theme(legend.position="none");Pro_Mcap_1212_plot
Pro_Mcap_1213_plot<-plot_bar(Pro_Mcap_1213, "Replicate", fill="its2_type_profile", title="1213")+
   theme(legend.position="none");Pro_Mcap_1213_plot

Pro_Mcap_1221_plot<-plot_bar(Pro_Mcap_1221, "Replicate", fill="its2_type_profile", title="1221")+
   theme(legend.position="none");Pro_Mcap_1221_plot
Pro_Mcap_1222_plot<-plot_bar(Pro_Mcap_1222, "Replicate", fill="its2_type_profile", title="1222")+
   theme(legend.position="none");Pro_Mcap_1222_plot
Pro_Mcap_1226_plot<-plot_bar(Pro_Mcap_1226, "Replicate", fill="its2_type_profile", title="1226")+
   theme(legend.position="none");Pro_Mcap_1226_plot
Pro_Mcap_1255_plot<-plot_bar(Pro_Mcap_1255, "Replicate", fill="its2_type_profile", title="1255")+
   theme(legend.position="none");Pro_Mcap_1255_plot
Pro_Mcap_1261_plot<-plot_bar(Pro_Mcap_1261, "Replicate", fill="its2_type_profile", title="1261")+
   theme(legend.position="none");Pro_Mcap_1261_plot
Pro_Mcap_1263_plot<-plot_bar(Pro_Mcap_1263, "Replicate", fill="its2_type_profile", title="1263")+
   theme(legend.position="none");Pro_Mcap_1263_plot
Pro_Mcap_1264_plot<-plot_bar(Pro_Mcap_1264, "Replicate", fill="its2_type_profile", title="1264")+
   theme(legend.position="none");Pro_Mcap_1264_plot
Pro_Mcap_127_plot<-plot_bar(Pro_Mcap_127, "Replicate", fill="its2_type_profile", title="127")+
   theme(legend.position="none");Pro_Mcap_127_plot
Pro_Mcap_1292_plot<-plot_bar(Pro_Mcap_1292, "Replicate", fill="its2_type_profile", title="1292")+
   theme(legend.position="none");Pro_Mcap_1292_plot
Pro_Mcap_141_plot<-plot_bar(Pro_Mcap_141, "Replicate", fill="its2_type_profile", title="141")+
   theme(legend.position="none");Pro_Mcap_141_plot
Pro_Mcap_146_plot<-plot_bar(Pro_Mcap_146, "Replicate", fill="its2_type_profile", title="146")+
   theme(legend.position="none");Pro_Mcap_146_plot
Pro_Mcap_151_plot<-plot_bar(Pro_Mcap_151, "Replicate", fill="its2_type_profile", title="151")+
   theme(legend.position="none");Pro_Mcap_151_plot
Pro_Mcap_160_plot<-plot_bar(Pro_Mcap_160, "Replicate", fill="its2_type_profile", title="160")+
   theme(legend.position="none");Pro_Mcap_160_plot
Pro_Mcap_211_plot<-plot_bar(Pro_Mcap_211, "Replicate", fill="its2_type_profile", title="211")+
   theme(legend.position="none");Pro_Mcap_211_plot
Pro_Mcap_258_plot<-plot_bar(Pro_Mcap_258, "Replicate", fill="its2_type_profile", title="258")+
   theme(legend.position="none");Pro_Mcap_258_plot
Pro_Mcap_277_plot<-plot_bar(Pro_Mcap_277, "Replicate", fill="its2_type_profile", title="277")+
   theme(legend.position="none");Pro_Mcap_277_plot
Pro_Mcap_306_plot<-plot_bar(Pro_Mcap_306, "Replicate", fill="its2_type_profile", title="306")+
   theme(legend.position="none");Pro_Mcap_306_plot
Pro_Mcap_315_plot<-plot_bar(Pro_Mcap_315, "Replicate", fill="its2_type_profile", title="315")+
   theme(legend.position="none");Pro_Mcap_315_plot
Pro_Mcap_322_plot<-plot_bar(Pro_Mcap_322, "Replicate", fill="its2_type_profile", title="22")+
   theme(legend.position="none");Pro_Mcap_322_plot
Pro_Mcap_32_plot<-plot_bar(Pro_Mcap_32, "Replicate", fill="its2_type_profile", title="32")+
   theme(legend.position="none");Pro_Mcap_32_plot
Pro_Mcap_333_plot<-plot_bar(Pro_Mcap_333, "Replicate", fill="its2_type_profile", title="333")+
   theme(legend.position="none");Pro_Mcap_333_plot
Pro_Mcap_353_plot<-plot_bar(Pro_Mcap_353, "Replicate", fill="its2_type_profile", title="353")+
   theme(legend.position="none");Pro_Mcap_353_plot
Pro_Mcap_386_plot<-plot_bar(Pro_Mcap_386, "Replicate", fill="its2_type_profile", title="386")+
   theme(legend.position="none");Pro_Mcap_386_plot
Pro_Mcap_479_plot<-plot_bar(Pro_Mcap_479, "Replicate", fill="its2_type_profile", title="479")+
   theme(legend.position="none");Pro_Mcap_479_plot
Pro_Mcap_485_plot<-plot_bar(Pro_Mcap_485, "Replicate", fill="its2_type_profile", title="485")+
   theme(legend.position="none");Pro_Mcap_485_plot
Pro_Mcap_497_plot<-plot_bar(Pro_Mcap_497, "Replicate", fill="its2_type_profile", title="497")+
   theme(legend.position="none");Pro_Mcap_497_plot
Pro_Mcap_556_plot<-plot_bar(Pro_Mcap_556, "Replicate", fill="its2_type_profile", title="556")+
   theme(legend.position="none");Pro_Mcap_556_plot
Pro_Mcap_565_plot<-plot_bar(Pro_Mcap_565, "Replicate", fill="its2_type_profile", title="565")+
   theme(legend.position="none");Pro_Mcap_565_plot
Pro_Mcap_576_plot<-plot_bar(Pro_Mcap_576, "Replicate", fill="its2_type_profile", title="576")+
   theme(legend.position="none");Pro_Mcap_576_plot
Pro_Mcap_586_plot<-plot_bar(Pro_Mcap_586, "Replicate", fill="its2_type_profile", title="586")+
   theme(legend.position="none");Pro_Mcap_586_plot
Pro_Mcap_609_plot<-plot_bar(Pro_Mcap_609, "Replicate", fill="its2_type_profile", title="609")+
   theme(legend.position="none");Pro_Mcap_609_plot
Pro_Mcap_612_plot<-plot_bar(Pro_Mcap_612, "Replicate", fill="its2_type_profile", title="612")+
   theme(legend.position="none");Pro_Mcap_612_plot
Pro_Mcap_620_plot<-plot_bar(Pro_Mcap_620, "Replicate", fill="its2_type_profile", title="620")+
   theme(legend.position="none");Pro_Mcap_620_plot
Pro_Mcap_632_plot<-plot_bar(Pro_Mcap_632, "Replicate", fill="its2_type_profile", title="632")+
   theme(legend.position="none");Pro_Mcap_632_plot
Pro_Mcap_649_plot<-plot_bar(Pro_Mcap_649, "Replicate", fill="its2_type_profile", title="649")+
   theme(legend.position="none");Pro_Mcap_649_plot
Pro_Mcap_670_plot<-plot_bar(Pro_Mcap_670, "Replicate", fill="its2_type_profile", title="670")+
   theme(legend.position="none");Pro_Mcap_670_plot
Pro_Mcap_677_plot<-plot_bar(Pro_Mcap_677, "Replicate", fill="its2_type_profile", title="677")+
   theme(legend.position="none");Pro_Mcap_677_plot
Pro_Mcap_684_plot<-plot_bar(Pro_Mcap_684, "Replicate", fill="its2_type_profile", title="684")+
   theme(legend.position="none");Pro_Mcap_684_plot
Pro_Mcap_70_plot<-plot_bar(Pro_Mcap_70, "Replicate", fill="its2_type_profile", title="70")+
   theme(legend.position="none");Pro_Mcap_70_plot
Pro_Mcap_742_plot<-plot_bar(Pro_Mcap_742, "Replicate", fill="its2_type_profile", title="742")+
   theme(legend.position="none");Pro_Mcap_742_plot
Pro_Mcap_748_plot<-plot_bar(Pro_Mcap_748, "Replicate", fill="its2_type_profile", title="748")+
   theme(legend.position="none");Pro_Mcap_748_plot
Pro_Mcap_78_plot<-plot_bar(Pro_Mcap_78, "Replicate", fill="its2_type_profile", title="78")+
   theme(legend.position="none");Pro_Mcap_78_plot
Pro_Mcap_823_plot<-plot_bar(Pro_Mcap_823, "Replicate", fill="its2_type_profile", title="823")+
   theme(legend.position="none");Pro_Mcap_823_plot
Pro_Mcap_83_plot<-plot_bar(Pro_Mcap_83, "Replicate", fill="its2_type_profile", title="83")+
   theme(legend.position="none");Pro_Mcap_83_plot
Pro_Mcap_95_plot<-plot_bar(Pro_Mcap_95, "Replicate", fill="its2_type_profile", title="95")+
   theme(legend.position="none");Pro_Mcap_95_plot

Mcap_DIV_PRO_plot1 <- ggarrange(Pro_Mcap_10_plot,Pro_Mcap_120_plot,Pro_Mcap_1212_plot,Pro_Mcap_1213_plot,Pro_Mcap_1221_plot,Pro_Mcap_1222_plot,Pro_Mcap_1226_plot,Pro_Mcap_1255_plot,
                    #labels = c("A", "B", "C","D","E","F","G","H"),
                    ncol = 4, nrow = 3);Mcap_DIV_PRO_plot1

Mcap_DIV_PRO_plot2 <- ggarrange(Pro_Mcap_1261_plot,Pro_Mcap_1263_plot,Pro_Mcap_1264_plot,Pro_Mcap_127_plot,Pro_Mcap_1292_plot,Pro_Mcap_141_plot,Pro_Mcap_146_plot,Pro_Mcap_151_plot,
                    #labels = c("A", "B", "C","D","E","F","G","H"),
                    ncol = 4, nrow = 3);Mcap_DIV_PRO_plot2

Mcap_DIV_PRO_plot3 <- ggarrange(Pro_Mcap_160_plot,Pro_Mcap_211_plot,Pro_Mcap_258_plot,Pro_Mcap_277_plot,Pro_Mcap_306_plot,Pro_Mcap_315_plot,Pro_Mcap_322_plot,Pro_Mcap_32_plot,
                    #labels = c("A", "B", "C","D","E","F","G","H"),
                    ncol = 4, nrow = 3);Mcap_DIV_PRO_plot3

Mcap_DIV_PRO_plot4 <- ggarrange(Pro_Mcap_333_plot,Pro_Mcap_353_plot,Pro_Mcap_386_plot,Pro_Mcap_479_plot,Pro_Mcap_485_plot,Pro_Mcap_497_plot,Pro_Mcap_556_plot,Pro_Mcap_565_plot,
                    #labels = c("A", "B", "C","D","E","F","G","H"),
                    ncol = 4, nrow = 3);Mcap_DIV_PRO_plot4

Mcap_DIV_PRO_plot5 <- ggarrange(Pro_Mcap_576_plot,Pro_Mcap_586_plot,Pro_Mcap_609_plot,Pro_Mcap_612_plot,Pro_Mcap_620_plot,Pro_Mcap_632_plot,Pro_Mcap_649_plot,Pro_Mcap_670_plot,
                    #labels = c("A", "B", "C","D","E","F","G","H"),
                    ncol = 4, nrow = 3);Mcap_DIV_PRO_plot5

Mcap_DIV_PRO_plot6 <- ggarrange(Pro_Mcap_677_plot,Pro_Mcap_684_plot,Pro_Mcap_70_plot,Pro_Mcap_742_plot,Pro_Mcap_748_plot,Pro_Mcap_78_plot,Pro_Mcap_823_plot,Pro_Mcap_83_plot,
                    #labels = c("A", "B", "C","D","E","F","G","H"),
                    ncol = 4, nrow = 3);Mcap_DIV_PRO_plot6

Mcap_DIV_PRO_plot7 <- ggarrange(Pro_Mcap_95_plot,
                    #labels = c("A", "B", "C","D","E","F","G","H"),
                    ncol = 4, nrow = 3);Mcap_DIV_PRO_plot7
```

Plots DIVS
```{r}  
coralDIV2.prune = prune_taxa(taxa_sums(coralDIV2.prune) > 0, coralDIV2.prune) #this removes any OTU with 0s
#plot_bar(coralDIV2.prune, "DIV", fill="DIV", facet_grid=~Colony)+theme(legend.position="none")
#for the legend
 plot_bar(Mcap_10,fill = "DIV")+
      geom_bar(aes(color=DIV, fill=DIV), stat="identity", position="stack")

Mcap_10_plot<-plot_bar(Mcap_10, "sample_name", fill="DIV", title="Mcap_10")+
   theme(legend.position="none");Mcap_10_plot
Mcap_120_plot<-plot_bar(Mcap_120, "sample_name", fill="DIV", title="Mcap_120")+
   theme(legend.position="none");Mcap_120_plot
Mcap_1212_plot<-plot_bar(Mcap_1212, "sample_name", fill="DIV", title="Mcap_1212")+
   theme(legend.position="none");Mcap_1212_plot
Mcap_1213_plot<-plot_bar(Mcap_1213, "sample_name", fill="DIV", title="Mcap_1213")+
   theme(legend.position="none");Mcap_1213_plot
Mcap_121_plot<-plot_bar(Mcap_121, "sample_name", fill="DIV", title="Mcap_121")+
   theme(legend.position="none");Mcap_121_plot
Mcap_1221_plot<-plot_bar(Mcap_1221, "sample_name", fill="DIV", title="Mcap_1221")+
   theme(legend.position="none");Mcap_1221_plot
Mcap_1222_plot<-plot_bar(Mcap_1222, "sample_name", fill="DIV", title="Mcap_1222")+
   theme(legend.position="none");Mcap_1222_plot
Mcap_1226_plot<-plot_bar(Mcap_1226, "sample_name", fill="DIV", title="Mcap_1226")+
   theme(legend.position="none");Mcap_1226_plot
Mcap_1255_plot<-plot_bar(Mcap_1255, "sample_name", fill="DIV", title="Mcap_1255")+
   theme(legend.position="none");Mcap_1255_plot
Mcap_1261_plot<-plot_bar(Mcap_1261, "sample_name", fill="DIV", title="Mcap_1261")+
   theme(legend.position="none");Mcap_1261_plot
Mcap_1263_plot<-plot_bar(Mcap_1263, "sample_name", fill="DIV", title="Mcap_1263")+
   theme(legend.position="none");Mcap_1263_plot
Mcap_1264_plot<-plot_bar(Mcap_1264, "sample_name", fill="DIV", title="Mcap_1264")+
   theme(legend.position="none");Mcap_1264_plot
Mcap_127_plot<-plot_bar(Mcap_127, "sample_name", fill="DIV", title="Mcap_127")+
   theme(legend.position="none");Mcap_127_plot
Mcap_1292_plot<-plot_bar(Mcap_1292, "sample_name", fill="DIV", title="Mcap_1292")+
   theme(legend.position="none");Mcap_1292_plot
Mcap_141_plot<-plot_bar(Mcap_141, "sample_name", fill="DIV", title="Mcap_141")+
   theme(legend.position="none");Mcap_141_plot
Mcap_146_plot<-plot_bar(Mcap_146, "sample_name", fill="DIV", title="Mcap_146")+
   theme(legend.position="none");Mcap_146_plot
Mcap_151_plot<-plot_bar(Mcap_151, "sample_name", fill="DIV", title="Mcap_151")+
   theme(legend.position="none");Mcap_151_plot
Mcap_160_plot<-plot_bar(Mcap_160, "sample_name", fill="DIV", title="Mcap_160")+
   theme(legend.position="none");Mcap_160_plot
Mcap_211_plot<-plot_bar(Mcap_211, "sample_name", fill="DIV", title="Mcap_211")+
   theme(legend.position="none");Mcap_211_plot
Mcap_258_plot<-plot_bar(Mcap_258, "sample_name", fill="DIV", title="Mcap_258")+
   theme(legend.position="none");Mcap_258_plot
Mcap_277_plot<-plot_bar(Mcap_277, "sample_name", fill="DIV", title="Mcap_277")+
   theme(legend.position="none");Mcap_277_plot
Mcap_306_plot<-plot_bar(Mcap_306, "sample_name", fill="DIV", title="Mcap_306")+
   theme(legend.position="none");Mcap_306_plot
Mcap_315_plot<-plot_bar(Mcap_315, "sample_name", fill="DIV", title="Mcap_315")+
   theme(legend.position="none");Mcap_315_plot
Mcap_322_plot<-plot_bar(Mcap_322, "sample_name", fill="DIV", title="Mcap_322")+
   theme(legend.position="none");Mcap_322_plot
Mcap_32_plot<-plot_bar(Mcap_32, "sample_name", fill="DIV", title="Mcap_32")+
   theme(legend.position="none");Mcap_32_plot
Mcap_333_plot<-plot_bar(Mcap_333, "sample_name", fill="DIV", title="Mcap_333")+
   theme(legend.position="none");Mcap_333_plot
Mcap_353_plot<-plot_bar(Mcap_353, "sample_name", fill="DIV", title="Mcap_353")+
   theme(legend.position="none");Mcap_353_plot
Mcap_386_plot<-plot_bar(Mcap_386, "sample_name", fill="DIV", title="Mcap_386")+
   theme(legend.position="none");Mcap_386_plot
Mcap_479_plot<-plot_bar(Mcap_479, "sample_name", fill="DIV", title="Mcap_479")+
   theme(legend.position="none");Mcap_479_plot
Mcap_485_plot<-plot_bar(Mcap_485, "sample_name", fill="DIV", title="Mcap_485")+
   theme(legend.position="none");Mcap_485_plot
Mcap_497_plot<-plot_bar(Mcap_497, "sample_name", fill="DIV", title="Mcap_497")+
   theme(legend.position="none");Mcap_497_plot
Mcap_556_plot<-plot_bar(Mcap_556, "sample_name", fill="DIV", title="Mcap_556")+
   theme(legend.position="none");Mcap_556_plot
Mcap_565_plot<-plot_bar(Mcap_565, "sample_name", fill="DIV", title="Mcap_565")+
   theme(legend.position="none");Mcap_565_plot
Mcap_576_plot<-plot_bar(Mcap_576, "sample_name", fill="DIV", title="Mcap_576")+
   theme(legend.position="none");Mcap_576_plot
Mcap_586_plot<-plot_bar(Mcap_586, "sample_name", fill="DIV", title="Mcap_586")+
   theme(legend.position="none");Mcap_586_plot
Mcap_609_plot<-plot_bar(Mcap_609, "sample_name", fill="DIV", title="Mcap_609")+
   theme(legend.position="none");Mcap_609_plot
Mcap_612_plot<-plot_bar(Mcap_612, "sample_name", fill="DIV", title="Mcap_612")+
   theme(legend.position="none");Mcap_612_plot
Mcap_620_plot<-plot_bar(Mcap_620, "sample_name", fill="DIV", title="Mcap_620")+
   theme(legend.position="none");Mcap_620_plot
Mcap_632_plot<-plot_bar(Mcap_632, "sample_name", fill="DIV", title="Mcap_632")+
   theme(legend.position="none");Mcap_632_plot
Mcap_649_plot<-plot_bar(Mcap_649, "sample_name", fill="DIV", title="Mcap_649")+
   theme(legend.position="none");Mcap_649_plot
Mcap_670_plot<-plot_bar(Mcap_670, "sample_name", fill="DIV", title="Mcap_670")+
   theme(legend.position="none");Mcap_670_plot
Mcap_677_plot<-plot_bar(Mcap_677, "sample_name", fill="DIV", title="Mcap_677")+
   theme(legend.position="none");Mcap_677_plot
Mcap_684_plot<-plot_bar(Mcap_684, "sample_name", fill="DIV", title="Mcap_684")+
   theme(legend.position="none");Mcap_684_plot
Mcap_70_plot<-plot_bar(Mcap_70, "sample_name", fill="DIV", title="Mcap_70")+
   theme(legend.position="none");Mcap_70_plot 
Mcap_742_plot<-plot_bar(Mcap_742, "sample_name", fill="DIV", title="Mcap_742")+
   theme(legend.position="none");Mcap_742_plot
Mcap_748_plot<-plot_bar(Mcap_748, "sample_name", fill="DIV", title="Mcap_748")+
   theme(legend.position="none");Mcap_748_plot
Mcap_78_plot<-plot_bar(Mcap_78, "sample_name", fill="DIV", title="Mcap_78")+
   theme(legend.position="none");Mcap_78_plot
Mcap_823_plot<-plot_bar(Mcap_823, "sample_name", fill="DIV", title="Mcap_823")+
   theme(legend.position="none");Mcap_823_plot
Mcap_83_plot<-plot_bar(Mcap_83, "sample_name", fill="DIV", title="Mcap_83")+
   theme(legend.position="none");Mcap_83_plot
Mcap_95_plot<-plot_bar(Mcap_95, "sample_name", fill="DIV", title="Mcap_95")+
   theme(legend.position="none");Mcap_95_plot
```